export type YoutubeVideoData = {
  _format_sort_fields: string[];
  _has_drm?: boolean;
  _type: string;
  _version: {
    current_git_head?: string;
    release_git_head: string;
    repository: string;
    version: string;
  };
  abr: number;
  acodec: string;
  age_limit: number;
  aspect_ratio: number;
  asr: number;
  audio_channels: number;
  automatic_captions: Record<string, Caption[]>;
  availability: string;
  average_rating?: number;
  categories: string[];
  channel: string;
  channel_follower_count: number;
  channel_id: string;
  channel_is_verified: boolean;
  channel_url: string;
  comment_count: number;
  description: string;
  display_id: string;
  duration: number;
  duration_string: string;
  dynamic_range: string;
  epoch: number;
  ext: string;
  extractor: string;
  extractor_key: string;
  filesize_approx: number;
  format: string;
  format_id: string;
  format_note: string;
  formats: Format[];
  fps: number;
  fulltitle: string;
  height: number;
  id: string;
  is_live: boolean;
  language: string;
  like_count: number;
  original_url: string;
  playable_in_embed: boolean;
  protocol: string;
  resolution: string;
  tbr: number;
  thumbnail: string;
  timestamp: number;
  title: string;
  upload_date: string;
  uploader: string;
  uploader_id: string;
  uploader_url: string;
  vbr: number;
  vcodec: string;
  view_count: number;
  was_live: boolean;
  webpage_url: string;
  webpage_url_basename: string;
  webpage_url_domain: string;
  width: number;
};

type Caption = { ext: string; name: string; url: string };

export type Format = {
  abr: number;
  acodec: string;
  aspect_ratio: number;
  asr?: number;
  audio_channels?: number;
  audio_ext: string;
  columns: number;
  dynamic_range: string;
  ext: string;
  filesize?: number;
  filesize_approx?: number;
  format: string;
  format_id: string;
  format_note: string;
  fps: number;
  fragments: Fragment[];
  height: number;
  protocol: string;
  quality: number;
  resolution: string;
  rows: number;
  tbr?: number;
  url: string;
  vbr: number;
  vcodec: string;
  video_ext: string;
  width: number;
};

type Fragment = {
  url: string;
  duration: number;
};
